matrix:
  include:
    - language: python
      python:
        - "2.7"
      install:
        - pip install -r requirements.txt
      script:
        - pytest

    - language: node_js
      node_js:
        - "node"
      before_install:
        - cd stories
      script:
        - npm test
