matrix:
  include:
    - language: python
      python:
        - "2.7"
      install:
        - pip install -r requirements.txt
      script:
        - pytest

    - language: node_js
      node_js:
        - "10.0.0"
      before_install:
        - cd stories
      install:
        - nvm install ls-remote
        - npm install
      script:
        - npm run test
